/*******************************************************************************
 * Verified Quaternion Test Vectors
 * 
 * Generated by: scripts/generate_test_vectors.py
 * Using: scipy.spatial.transform.Rotation
 * Date: 2025-10-11
 * 
 * Quaternion format: [q0, q1, q2, q3] = [w, x, y, z]
 ******************************************************************************/

#ifndef TEST_VECTORS_QUAT_H
#define TEST_VECTORS_QUAT_H

#include "algo_sf_quatmath.h"

// Identity quaternion (no rotation)
quaternion_double_t test_quat_identity = {1.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00};

// 90° rotation around X-axis
quaternion_double_t test_quat_rot_x_90deg = {7.07106781186547573e-01, 7.07106781186547462e-01, 0.00000000000000000e+00, 0.00000000000000000e+00};

// 90° rotation around Y-axis
quaternion_double_t test_quat_rot_y_90deg = {7.07106781186547573e-01, 0.00000000000000000e+00, 7.07106781186547462e-01, 0.00000000000000000e+00};

// 90° rotation around Z-axis
quaternion_double_t test_quat_rot_z_90deg = {7.07106781186547573e-01, 0.00000000000000000e+00, 0.00000000000000000e+00, 7.07106781186547462e-01};

// 45° rotation around [1,1,1] axis
quaternion_double_t test_quat_rot_arbitrary_45deg = {9.23879532511286738e-01, 2.20942382690394568e-01, 2.20942382690394568e-01, 2.20942382690394568e-01};

// Product of X90 and Y90 rotations
quaternion_double_t test_quat_product_x90_y90_input1 = {7.07106781186547573e-01, 7.07106781186547462e-01, 0.00000000000000000e+00, 0.00000000000000000e+00};
quaternion_double_t test_quat_product_x90_y90_input2 = {7.07106781186547573e-01, 0.00000000000000000e+00, 7.07106781186547462e-01, 0.00000000000000000e+00};
quaternion_double_t test_quat_product_x90_y90_expected = {5.00000000000000111e-01, 5.00000000000000000e-01, 5.00000000000000000e-01, 4.99999999999999889e-01};

// X90 quaternion to rotation matrix
quaternion_double_t test_quat_quat_to_rotmtx_x90 = {7.07106781186547573e-01, 7.07106781186547462e-01, 0.00000000000000000e+00, 0.00000000000000000e+00};
double test_rotmtx_quat_to_rotmtx_x90[3][3] = {
    {1.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00},
    {0.00000000000000000e+00, 2.22044604925031308e-16, -1.00000000000000000e+00},
    {0.00000000000000000e+00, 1.00000000000000000e+00, 2.22044604925031308e-16}
};
quaternion_double_t test_quat_quat_to_rotmtx_x90_expected = {7.07106781186547573e-01, 7.07106781186547462e-01, 0.00000000000000000e+00, 0.00000000000000000e+00};

// Y90 rotation matrix to quaternion
quaternion_double_t test_quat_rotmtx_to_quat_y90 = {7.07106781186547573e-01, 0.00000000000000000e+00, 7.07106781186547462e-01, 0.00000000000000000e+00};
double test_rotmtx_rotmtx_to_quat_y90[3][3] = {
    {2.22044604925031308e-16, 0.00000000000000000e+00, 1.00000000000000000e+00},
    {0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00},
    {-1.00000000000000000e+00, 0.00000000000000000e+00, 2.22044604925031308e-16}
};
quaternion_double_t test_quat_rotmtx_to_quat_y90_expected = {7.07106781186547573e-01, 0.00000000000000000e+00, 7.07106781186547462e-01, 0.00000000000000000e+00};

// Euler angles (30°, 45°, 60°) to quaternion
quaternion_double_t test_quat_euler_30_45_60 = {8.22363171905999391e-01, 2.22600267147338160e-02, 4.39679739540909553e-01, 3.60423405650355910e-01};
double test_angles_euler_30_45_60[3] = {3.00000000000000000e+01, 4.50000000000000000e+01, 6.00000000000000000e+01}; // roll, pitch, yaw in degrees
quaternion_double_t test_quat_euler_30_45_60_expected = {8.22363171905999391e-01, 2.22600267147338160e-02, 4.39679739540909553e-01, 3.60423405650355910e-01};

// Integrate ω=[0,0,10] rad/s for 0.1s
double test_omega_integrate_omega_z10[3] = {0.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+01}; // rad/s
double test_dt_integrate_omega_z10 = 1.00000000000000006e-01; // seconds
quaternion_double_t test_quat_integrate_omega_z10_expected = {8.77582561890372759e-01, 0.00000000000000000e+00, 0.00000000000000000e+00, 4.79425538604203005e-01};

#endif // TEST_VECTORS_QUAT_H
